<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5ZWG5a625ZCI5L2c');
$cfg_Cs[2]=array(0,1,1,'572R57qi5byA5bqX');
$cfg_Cs[3]=array(0,1,1,'55u05pKt55S15ZWG');
$cfg_Cs[4]=array(0,1,1,'5qGI5L6L5YiG5Lqr');
$cfg_Cs[5]=array(0,1,1,'5ZCI5L2c5ZOB54mM');
$cfg_Cs[6]=array(0,1,1,'5pyN5Yqh5L2T57O7');
$cfg_Cs[19]=array(0,1,1,'6L+Z5Lqb6L6+5Lq66YO95Zyo55So');
$cfg_Cs[16]=array(4,1,1,'576O5aaG5Liq5oqk');
$cfg_Cs[22]=array(4,1,1,'5pyN6aWw566x5YyF');
$cfg_Cs[17]=array(4,1,1,'55Sf5rS755m+6LSn');
$cfg_Cs[18]=array(4,1,1,'6aOf5ZOB6aWu5paZ');
$cfg_Cs[20]=array(0,1,1,'5a6Y5pa55bim6LSn5bCP56iL5bqP');
$cfg_Cs[23]=array(2,1,1,'572R57qi5byA5bqX');
?>