<?php
$typeArr[1] = '关于我们';
$typeArr[50] = '联系方式';
$typeArr[51] = '在线留言';
$typeArr[2] = '公司简介';
$typeArr[3] = '企业文化';
$typeArr[4] = '合作伙伴';
$typeArr[5] = '产品中心';
$typeArr[6] = '产品分类1';
$typeArr[7] = '产品分类2';
$typeArr[12] = '新闻中心';
$typeArr[13] = '公司新闻';
$typeArr[14] = '行业资讯';
$typeArr[15] = '项目管理及实施';
$typeArr[16] = '弱电系统工程';
$typeArr[17] = '行业解决方案';
$typeArr[22] = '服务中心';
$typeArr[45] = '人才招聘';
$typeArr[33] = '联系方式';
$typeArr[47] = '产品分类3';
$typeArr[48] = '产品分类4';
$typeArr[46] = '合作伙伴';
$typeArr[49] = '项目案例';
?>