<?php
$z[0]=Array("field","",228,257);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n				<div class=\"banner__item\"> <img style=\"width:144px;height:39px\" src=\"[field:litpic/]\" alt=\"[field:title/]\"> </div>\r\n				",347,556);
$z[1][4]=array();
$z[1][4]['typeid']="";
$z[1][4]['limit']="0,6";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("arclist","\r\n				<div class=\"banner__item\"> <img style=\"width:144px;height:39px\" src=\"[field:litpic/]\" alt=\"[field:title/]\"> </div>\r\n				",641,850);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['limit']="6,6";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n				<div class=\"banner__item\"> <img style=\"width:144px;height:39px\" src=\"[field:litpic/]\" alt=\"[field:title/]\"> </div>\r\n				",935,1145);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['limit']="16,6";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";

?>