<?php
$z[0]=Array("field","",154,186);
$z[0][4]=array();
$z[0][4]['name']="description";
$z[1]=Array("arclist","\r\n			  <div class=\"business__banner__text__item[field:global runphp='yes' name=autoindex]\r\n                      \$a=\"\";\r\n                        \$b=\" business__banner__text__item--active\";\r\n                        if ((@me%1)==0 && @me!=1)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        [/field:global]\">\r\n                <h3 class=\"business__banner__text__item__title\"> [field:title/] </h3>\r\n                <p class=\"business__banner__text__item__content\"> [field:description function=\"cn_substr(@me,300)\"/]</p>\r\n              </div>\r\n			  ",300,947);
$z[1][4]=array();
$z[1][4]['typeid']="";
$z[1][4]['row']="4";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("arclist","\r\n				  <div class=\"swiper-slide\"> <img style=\"width: 400px;height: 390px;\" src=\"[field:litpic/]\" alt=\"\"> </div>\r\n				  ",1166,1365);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="4";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";

?>