<?php
$z[0]=Array("field","",207,239);
$z[0][4]=array();
$z[0][4]['name']="description";
$z[1]=Array("arclist","\r\n				  <div class=\"swiper-slide\"> <img src=\"[field:litpic/]\" alt=\"\"> </div>\r\n				  ",463,626);
$z[1][4]=array();
$z[1][4]['typeid']="";
$z[1][4]['row']="3";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("arclist","\r\n			  <div class=\"celebrity__banner__text__item\">\r\n                <h3 class=\"celebrity__banner__text__item__title\">[field:title/]</h3>\r\n                <p class=\"celebrity__banner__text__item__content\"> [field:description function=\"cn_substr(@me,300)\"/] </p>\r\n              </div>\r\n			  ",873,1241);
$z[2][4]=array();
$z[2][4]['typeid']="";
$z[2][4]['row']="3";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";

?>