<?php
$z[0]=Array("global","\r\n                      \$a=\"\";\r\n                        \$b=\" business__banner__text__item--active\";\r\n                        if ((@me%1)==0 && @me!=1)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",40,321);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("title","",390,404);
$z[1][4]=array();
$z[2]=Array("description","",478,528);
$z[2][4]=array();
$z[2][4]['function']="cn_substr(@me,300)";

?>