<?php
$z[0]=Array("global","",148,172);
$z[0][4]=array();
$z[0][4]['name']="itemindex";
$z[1]=Array("field","",258,287);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("global","",360,384);
$z[2][4]=array();
$z[2][4]['name']="itemindex";
$z[3]=Array("field","",541,570);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("arclist","\r\n				  <div class=\"good__mask__item\">\r\n                    <div class=\"good__mask__item__image\"> <img src=\"[field:litpic/]\" alt=\"\" class=\"good__mask__item__image\"> </div>\r\n                    <h6 class=\"good__mask__item__title\"> [field:title/] </h6>\r\n                    <p class=\"good__mask__item__content\"> [field:shorttitle/] </p>\r\n                  </div>\r\n				  ",595,1042);
$z[4][4]=array();
$z[4][4]['typeid']="";
$z[4][4]['row']="2";
$z[4][4]['titlelen']="60";
$z[4][4]['orderby']="pubdate";

?>