<div class="system__wrapper">
              <div class="system">
                <div style="background-image: url('/skin/images/wh_tx[field:global.autoindex/].png');"
                                        class="image"> <img style="width:46px" src="/skin/images/wh_tx[field:global.autoindex/]_icon.png" alt=""> </div>
                <h5 class="system__title">[field:title/]</h5>
                <div class="system__mask">
                  <h6 class="system__mask__title"> [field:title/] </h6>
                  <p class="system__mask__cotnent"> [field:description function="cn_substr(@me,300)"/] </p>
                  <a href="javascript:;" target="blank">
                  <p class="system__mask__link"> 了解更多 </p>
                  </a>
                  <button class="btn btn-primary system__mask__button btn-open-immediately"> 立即开通 </button>
                </div>
              </div>
            </div>