<?php
$z[0]=Array("field","",68,97);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n			  <div class=\"portrait\">\r\n                <div class=\"img\"> <img src=\"/skin/images/1.png\"> </div>\r\n                <h6 class=\"portrait__title\">[field:title/]</h6>\r\n                <p class=\"portrait__mark\">粉丝量：[field:shorttitle/]</p>\r\n              </div>\r\n			  ",207,562);
$z[1][4]=array();
$z[1][4]['typeid']="";
$z[1][4]['row']="15";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";

?>