<div class="swiper-slide" style="background-image:url('[field:pic/]')">
            <div class="swiper-slide__container">
              <h1 class="swiper-slide__container__title"></h1>
              <h3 class="swiper-slide__container__content"></h3>
              <div class="btn-group">
                <button class="btn btn-large btn-immediatelyOpen btn-open-immediately">立即开通</button>
              </div>
            </div>
          </div>