<?php
$z[0]=Array("global","",218,244);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",288,318);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",355,382);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1366,1401);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("myppt","\r\n		  <div class=\"swiper-slide\" style=\"background-image:url('[field:pic/]')\">\r\n            <div class=\"swiper-slide__container\">\r\n              <h1 class=\"swiper-slide__container__title\"></h1>\r\n              <h3 class=\"swiper-slide__container__content\"></h3>\r\n              <div class=\"btn-group\">\r\n                <button class=\"btn btn-large btn-immediatelyOpen btn-open-immediately\">立即开通</button>\r\n              </div>\r\n            </div>\r\n          </div>\r\n		  ",1556,2065);
$z[4][4]=array();
$z[4][4]['typeid']="2";
$z[5]=Array("global","",2262,2288);
$z[5][4]=array();
$z[5][4]['name']="cfg_webname";
$z[6]=Array("field","",2662,2691);
$z[6][4]=array();
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n			  <div class=\"celebrity__banner__text__item\">\r\n                <h3 class=\"celebrity__banner__text__item__title\">[field:title/]</h3>\r\n                <p class=\"celebrity__banner__text__item__content\"> [field:description function=\"cn_substr(@me,300)\"/] </p>\r\n              </div>\r\n			  ",2822,3150);
$z[7][4]=array();
$z[7][4]['pagesize']="999";
$z[8]=Array("include","",3244,3281);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>